@startuml infra
node node [

Rouge = Send of Log

----

Vert = Send/Receive of request

----

Noir = Outgoing flux

----

Orange = Load Balancing

]
cloud Clever_cloud{
    rectangle "Otoroshi\nReverse Proxy\nWebAuth(JWT)\nAnd more" as oto
    database Mongodb as mongo
    node "Api B2B 1 " as ms1
    node "Api B2B 2" as ms2
    node Microservice3 as ms3
    node Serveur_de_log as log
    cloud "Api + Static content or no"{
        interface  FrontOffice as fo
        interface  BackOffice as bo
    }
}
node The_World as us{
    Actor BusinessUser as bu
    Actor AdminUser as au
    Actor Teacher as te
}


ms1 -[#red]-> log : Send of log
ms2 -[#red]-> log
ms3 --[#red]> log
oto-[#red]-> log 
bo <-[#red]-> log 
fo -[#red]-> log 

mongo -[#green]-> oto :Only accessible by the member\n of the recognized service

oto <-[#Orange]-> ms1 : Load Balancing

oto <-[#Orange]-> ms2 

oto <-[#green]-> ms3

oto <=[#black]=> us : Access outside of the authentified part

oto <-[#green]-> fo

oto <-[#green]-> bo


@enduml